channels:
  - bioconda
  - conda-forge
  - mpi-ie 
  - defaults
dependencies:
  - ipdb==0.13.7
  - pygenometracks==3.6
  - pandas==1.2.3
  - openpyxl==3.0.7
  - matplotlib==3.3.2
  - matplotlib-venn==0.11.6
  - seaborn==0.11.1
  - pybedtools==0.8.2
  - pip
  - xlsxwriter==1.4.3
  - pyensembl==1.9.1
  - ucsc-bigwigtowig
  - requests
  - ucsc-wigtobigwig
  - deeptools
  - snakepipes
  - bioconductor-complexheatmap
  - r-dplyr
  - r-openxlsx
