UMIBarcode: false
UMIDedup: false
UMIDedupOpts: --paired
UMIDedupSep: _
absBestLFC: 0
bamExt: .filtered.bam
baseDir: /home/schamori/anaconda3/envs/snakePipes3/lib/python3.7/site-packages/snakePipes
bcPattern: NNNNCCCCCCCCC
bwBinSize: 4
clusterConfig: shared/cluster.yaml
clusterConfigFile: null
configFile: config.yaml
configMode: manual
createDAG: false
emailAddress: null
emailSender: null
fastqc: null
fdr: 1.0
filterGTF: null
fragmentCountThreshold: 1
fragmentLength: null
fromBAM: null
genome: GRCm38_release98
keepTemp: false
local: true
maxFragmentSize: 150
maxJobs: 25
minFragmentSize: 0
oldConfig: null
onlySSL: false
organismsDir: shared/organisms
outdir: /home/schamori/snakePipes/atac-seq-no-fdr
pairedEnd: true
peakCaller: MACS2
pipeline: ATAC-seq
plotFormat: png
qval: 0.05
sampleSheet: /home/schamori/snakePipes/atac-seq-no-fdr/Dicer_diff_atac.tsv
smtpPassword: null
smtpPort: 0
smtpServer: null
smtpUsername: null
snakemakeOptions: ' --use-conda --conda-prefix /home/schamori/anaconda3/envs \--verbose
  --printshellcmds'
tempDir: /home/schamori/tmp
toolsVersion: true
trim: null
verbose: false
windowSize: 20
workingdir: /home/schamori/snakePipes/atac-seq-no-fdr
