GCBias: false
NMaskedIndex: ''
SNPfile: ''
UMIBarcode: false
UMIDedup: false
UMIDedupOpts: null
UMIDedupSep: _
VCFfile: ''
aligner: Bowtie2
alignerOpts: null
allele_mode: null
baseDir: /home/schamori/anaconda3/envs/snakePipes2/lib/python3.6/site-packages/snakePipes
bcPattern: NNNNCCCCCCCC
bwBinSize: 25
clusterConfig: shared/cluster.yaml
clusterConfigFile: null
configFile: null
createDAG: false
dedup: true
downsample: null
emailAddress: null
emailSender: null
ext: .fastq.gz
fastqc: true
fragmentLength: 200
genome: GRCm38_release98
indir: /cclab_nas/rawdata/ATAC-seq/fastq
insertSizeMax: 1000
keepTemp: false
local: true
mapq: 3
mateOrientation: --fr
maxJobs: 32
mode: mapping
onlySSL: false
organismsDir: shared/organisms
outdir: /home/schamori/snakePipes/atac-seq-ago122
pipeline: dna-mapping
plotFormat: png
properPairs: false
qualimap: false
reads:
- _R1
- _R2
smtpPassword: null
smtpPort: 0
smtpServer: null
smtpUsername: null
snakemakeOptions: ' --use-conda --conda-prefix /home/schamori/anaconda3/envs '
strains: ''
tempDir: /home/schamori/tmp/
toolsVersion: true
trim: true
trimmer: trimgalore
trimmerOptions: --nextera --paired
verbose: false
workingdir: /home/schamori/snakePipes/atac-seq-ago122
