import matplotlib.pyplot as plt
import pandas as pd
import pyensembl
import seaborn as sns

ensembl_release = pyensembl.EnsemblRelease(98, pyensembl.species.mouse)

# tss_with_encode_normalized.bed is either generated by tss_chip_heatmaps.sh or provided in Table S2
df = pd.read_csv('tss_with_encode_normalized.bed', sep='\t')

fig, ax = plt.subplots(figsize=(5, 5))
ax.axvline(0, color='black')
ax.axhline(0.5, color='black')
cluster_colors = {'cluster_1': '#2b327f', 'cluster_2': '#5483be', 'cluster_3': '#a9cd82', 'cluster_4': '#eda043'}

ago12_deg = pd.read_excel('../../data/TableS1_RNA-seq_V3-cc.xlsx', index_col=[0, 1], header=[0, 1], skiprows=2).droplevel(level=1, axis=0)[('Ago2&1', 'log2FoldChange')]

for cluster_name, cluster_data in df.groupby('deepTools_group'):
    genes = cluster_data['name'].apply(lambda v: ensembl_release.transcript_by_id(v).gene_id).dropna()
    l2fc = ago12_deg.loc[genes]
    sns.ecdfplot(l2fc, label=cluster_name, ax=ax, color=cluster_colors[cluster_name])

ax.set_xlim([-1, 1])
ax.legend()
ax.grid(False)
sns.despine()
fig.savefig('h3k9me27_clusters_deg_cdf.png')
